# Form implementation generated from reading ui file '/home/peach/Uni/mnGui/src/ui/add_switch_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 325)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(80, 270, 181, 32))
        self.button_box.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 299, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.full_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.full_layout.setContentsMargins(0, 0, 0, 0)
        self.full_layout.setObjectName("full_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.setObjectName("form_layout")
        self.switch_label = QtWidgets.QLabel(self.layoutWidget)
        self.switch_label.setObjectName("switch_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.switch_label)
        self.switch_list = QtWidgets.QListWidget(self.layoutWidget)
        self.switch_list.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.switch_list.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.switch_list.setObjectName("switch_list")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.switch_list)
        self.switch_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.switch_name_label.setObjectName("switch_name_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.switch_name_label)
        self.switch_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.switch_name.setEnabled(False)
        self.switch_name.setMaxLength(6)
        self.switch_name.setObjectName("switch_name")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.switch_name)
        self.dpid_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.dpid_name_label.setObjectName("dpid_name_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dpid_name_label)
        self.dpid_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.dpid_name.setEnabled(False)
        self.dpid_name.setObjectName("dpid_name")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dpid_name)
        self.full_layout.addLayout(self.form_layout)
        self.checkbox_layout = QtWidgets.QHBoxLayout()
        self.checkbox_layout.setObjectName("checkbox_layout")
        self.auto_name = QtWidgets.QCheckBox(self.layoutWidget)
        self.auto_name.setChecked(True)
        self.auto_name.setObjectName("auto_name")
        self.checkbox_layout.addWidget(self.auto_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.full_layout.addLayout(self.checkbox_layout)
        self.full_layout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Switch"))
        self.switch_label.setText(_translate("Dialog", "Connect to"))
        self.switch_name_label.setText(_translate("Dialog", "Switch Name"))
        self.dpid_name_label.setText(_translate("Dialog", "DPID"))
        self.auto_name.setText(_translate("Dialog", "AutoFill Name"))
