# Form implementation generated from reading ui file '/home/peach/Uni/mnGui/src/ui/add_flow_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(429, 220)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 7, 0, 1, 1)
        self.full_layout = QtWidgets.QVBoxLayout()
        self.full_layout.setObjectName("full_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.setHorizontalSpacing(20)
        self.form_layout.setObjectName("form_layout")
        self.dpid_label = QtWidgets.QLabel(Dialog)
        self.dpid_label.setObjectName("dpid_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dpid_label)
        self.dpid_text = QtWidgets.QLabel(Dialog)
        self.dpid_text.setObjectName("dpid_text")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dpid_text)
        self.match_label = QtWidgets.QLabel(Dialog)
        self.match_label.setObjectName("match_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.match_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.source_label = QtWidgets.QLabel(Dialog)
        self.source_label.setObjectName("source_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.source_label)
        self.source_box = QtWidgets.QComboBox(Dialog)
        self.source_box.setObjectName("source_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.source_box)
        self.destination_label = QtWidgets.QLabel(Dialog)
        self.destination_label.setObjectName("destination_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.destination_label)
        self.destination_box = QtWidgets.QComboBox(Dialog)
        self.destination_box.setObjectName("destination_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.destination_box)
        self.in_port_label = QtWidgets.QLabel(Dialog)
        self.in_port_label.setObjectName("in_port_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.in_port_label)
        self.in_port_box = QtWidgets.QSpinBox(Dialog)
        self.in_port_box.setObjectName("in_port_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.in_port_box)
        self.form_layout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.out_port_box = QtWidgets.QSpinBox(Dialog)
        self.out_port_box.setObjectName("out_port_box")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.out_port_box)
        self.out_port_label = QtWidgets.QLabel(Dialog)
        self.out_port_label.setObjectName("out_port_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.out_port_label)
        self.form_layout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formLayout_2)
        self.actions_label = QtWidgets.QLabel(Dialog)
        self.actions_label.setObjectName("actions_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.actions_label)
        self.priority_label = QtWidgets.QLabel(Dialog)
        self.priority_label.setObjectName("priority_label")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priority_label)
        self.priority_box = QtWidgets.QSpinBox(Dialog)
        self.priority_box.setObjectName("priority_box")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priority_box)
        self.full_layout.addLayout(self.form_layout)
        self.full_layout.setStretch(0, 3)
        self.gridLayout.addLayout(self.full_layout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Flow Details"))
        self.dpid_label.setText(_translate("Dialog", "DPID"))
        self.dpid_text.setText(_translate("Dialog", "1"))
        self.match_label.setText(_translate("Dialog", "Match"))
        self.source_label.setText(_translate("Dialog", "Source"))
        self.destination_label.setText(_translate("Dialog", "Destination"))
        self.in_port_label.setText(_translate("Dialog", "In Port"))
        self.out_port_label.setText(_translate("Dialog", "Output Port"))
        self.actions_label.setText(_translate("Dialog", "Actions"))
        self.priority_label.setText(_translate("Dialog", "Priority"))
