# Form implementation generated from reading ui file '/home/peach/Uni/mnGui/src/ui/flow_details_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(374, 329)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.full_layout = QtWidgets.QVBoxLayout()
        self.full_layout.setObjectName("full_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.setHorizontalSpacing(20)
        self.form_layout.setObjectName("form_layout")
        self.priority_label = QtWidgets.QLabel(Dialog)
        self.priority_label.setObjectName("priority_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priority_label)
        self.priority_text = QtWidgets.QLabel(Dialog)
        self.priority_text.setObjectName("priority_text")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priority_text)
        self.match_label = QtWidgets.QLabel(Dialog)
        self.match_label.setObjectName("match_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.match_label)
        self.actions_label = QtWidgets.QLabel(Dialog)
        self.actions_label.setObjectName("actions_label")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.actions_label)
        self.table_label = QtWidgets.QLabel(Dialog)
        self.table_label.setObjectName("table_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.table_label)
        self.table_text = QtWidgets.QLabel(Dialog)
        self.table_text.setObjectName("table_text")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.table_text)
        self.match_box = QtWidgets.QTextBrowser(Dialog)
        self.match_box.setObjectName("match_box")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.match_box)
        self.actions_box = QtWidgets.QTextBrowser(Dialog)
        self.actions_box.setObjectName("actions_box")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.actions_box)
        self.full_layout.addLayout(self.form_layout)
        self.full_layout.setStretch(0, 3)
        self.gridLayout.addLayout(self.full_layout, 0, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 7, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Flow Details"))
        self.priority_label.setText(_translate("Dialog", "Priority"))
        self.priority_text.setText(_translate("Dialog", "1"))
        self.match_label.setText(_translate("Dialog", "Match"))
        self.actions_label.setText(_translate("Dialog", "Actions"))
        self.table_label.setText(_translate("Dialog", "Table ID"))
        self.table_text.setText(_translate("Dialog", "0"))
