# Form implementation generated from reading ui file '/home/peach/Uni/mnGui/src/ui/send_requests_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 272)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.full_layout = QtWidgets.QVBoxLayout()
        self.full_layout.setObjectName("full_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.setObjectName("form_layout")
        self.switch_label = QtWidgets.QLabel(Dialog)
        self.switch_label.setObjectName("switch_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.switch_label)
        self.client_box = QtWidgets.QComboBox(Dialog)
        self.client_box.setObjectName("client_box")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.client_box)
        self.type_label = QtWidgets.QLabel(Dialog)
        self.type_label.setObjectName("type_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.type_label)
        self.server_box = QtWidgets.QComboBox(Dialog)
        self.server_box.setObjectName("server_box")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.server_box)
        self.switch_name_label = QtWidgets.QLabel(Dialog)
        self.switch_name_label.setObjectName("switch_name_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.switch_name_label)
        self.hash_box = QtWidgets.QLineEdit(Dialog)
        self.hash_box.setEnabled(True)
        self.hash_box.setMaxLength(30)
        self.hash_box.setObjectName("hash_box")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.hash_box)
        self.switch_name_label_2 = QtWidgets.QLabel(Dialog)
        self.switch_name_label_2.setObjectName("switch_name_label_2")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.switch_name_label_2)
        self.response_box = QtWidgets.QTextBrowser(Dialog)
        self.response_box.setObjectName("response_box")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.response_box)
        self.full_layout.addLayout(self.form_layout)
        self.full_layout.setStretch(0, 3)
        self.gridLayout.addLayout(self.full_layout, 0, 0, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 2, 0, 1, 1)
        self.checkbox_layout = QtWidgets.QHBoxLayout()
        self.checkbox_layout.setObjectName("checkbox_layout")
        self.send_btn = QtWidgets.QPushButton(Dialog)
        self.send_btn.setEnabled(True)
        self.send_btn.setObjectName("send_btn")
        self.checkbox_layout.addWidget(self.send_btn)
        self.gridLayout.addLayout(self.checkbox_layout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Send Requests"))
        self.switch_label.setText(_translate("Dialog", "Client"))
        self.type_label.setText(_translate("Dialog", "Server"))
        self.switch_name_label.setText(_translate("Dialog", "To hash"))
        self.switch_name_label_2.setText(_translate("Dialog", "Response"))
        self.send_btn.setText(_translate("Dialog", "Send Request"))
